spring.application.name=saborgourmet
spring.datasource.url=jdbc:postgresql://localhost:5432/saborgourmetdb
spring.datasource.username=saborgourmetuser
spring.datasource.password=pass1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true